// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJjB6MU-LVP6Mibpd03xllZ4O3EZ3QPm4',
    appId: '1:664851867123:web:0219364cbbcd7ee8799e86',
    messagingSenderId: '664851867123',
    projectId: 'flutterchatapp-668cf',
    authDomain: 'flutterchatapp-668cf.firebaseapp.com',
    storageBucket: 'flutterchatapp-668cf.appspot.com',
    measurementId: 'G-91LDDY1XW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCagFCsMd_Ik6ySbUpEK47_ki99ltK6mVg',
    appId: '1:664851867123:android:85f8f61cb631efd2799e86',
    messagingSenderId: '664851867123',
    projectId: 'flutterchatapp-668cf',
    storageBucket: 'flutterchatapp-668cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkKTeTv31Cjt-uoQMRUCHNTf4uQy1pR0E',
    appId: '1:664851867123:ios:de82c63d55748e8d799e86',
    messagingSenderId: '664851867123',
    projectId: 'flutterchatapp-668cf',
    storageBucket: 'flutterchatapp-668cf.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkKTeTv31Cjt-uoQMRUCHNTf4uQy1pR0E',
    appId: '1:664851867123:ios:de82c63d55748e8d799e86',
    messagingSenderId: '664851867123',
    projectId: 'flutterchatapp-668cf',
    storageBucket: 'flutterchatapp-668cf.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJjB6MU-LVP6Mibpd03xllZ4O3EZ3QPm4',
    appId: '1:664851867123:web:7c4532ac5d94ae56799e86',
    messagingSenderId: '664851867123',
    projectId: 'flutterchatapp-668cf',
    authDomain: 'flutterchatapp-668cf.firebaseapp.com',
    storageBucket: 'flutterchatapp-668cf.appspot.com',
    measurementId: 'G-96Z5LGX9EV',
  );
}
